# alpine, busybox, scratch
FROM ubuntu:latest
COPY proxy-admin /
#RUN proxy-admin install

#COPY Shanghai /etc/localtime/
#COPY ca-certificates.crt /etc/ssl/certs/
#ENTRYPOINT ["/bin/sh"]

#ENTRYPOINT ["/proxy"]
#CMD ["http" "-t" "tcp" "-p" "0.0.0.0:8081" "--daemon"]

#/proxy http -t tcp -p "0.0.0.0:8081" --daemon
#CMD ["--version"]