---
version: '3.9'

services:
  regoproxy:
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:32080

